name: Publish

on:
  push:
    branches:
      - src

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - name: Initialize bot 
      run: |
        git config --global user.name "CI Bot"
        git config --global user.email "none@email.com"
    - name: Checkout src
      uses: actions/checkout@v2
      with: 
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Compile src and publish to gh-pages
      run: ./publish.sh
      shell: bash
      
      
