name: Publish

on:
  push:
    branches:
      - src

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - name: Checkout src
      uses: actions/checkout@v2
      
    - name: Add permissions
      run: chmod +x ./publish.sh
      shell: bash
      
    - name: Compile src and publish to gh-pages
      run: ./publish.sh
      shell: bash
      
