name: Publish

on:
  push:
    branches:
      - src

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: | 
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        
    - name: Initialize bot 
      run: |
        git config --global user.name "CI Bot"
        git config --global user.email "none@email.com"
        
    - name: Compile src and publish to gh-pages
      run: ./publish.sh
      shell: bash
      
      
